apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: text-to-cad-discord-bot-secrets
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: text-to-cad-discord-bot-secrets
    template:
      data:
          discord_bot_token: "{{ .discordToken }}"
          discord_client_id: "{{ .discordClientId }}"
          discord_client_secret: "{{ .discordClientSecret }}"
          discord_redirect_uri: "{{ .discordRedirectUri }}"
  data:
    - secretKey: discordToken
      remoteRef:
        key: /corp/text-to-cad-discord-bot/discord
        property: token
    - secretKey: discordClientId
      remoteRef:
        key: /corp/text-to-cad-discord-bot/discord
        property: client_id
    - secretKey: discordClientSecret
      remoteRef:
        key: /corp/text-to-cad-discord-bot/discord
        property: client_secret
    - secretKey: discordRedirectUri
      remoteRef:
        key: /corp/text-to-cad-discord-bot/discord
        property: redirect_uri
