name: docker-image
permissions:
  packages: write
  contents: read
on:
  pull_request:
    paths:
      - "**.rs"
      - "**.rs.gen"
      - Cargo.toml
      - Cargo.lock
      - "rust-toolchain"
      - "rust-toolchain.toml"
      - "Dockerfile"
      - .github/workflows/docker-image.yml
  workflow_call:
  workflow_dispatch:
    inputs:
concurrency:
  group: docker-image-${{ github.ref }}
  cancel-in-progress: false
jobs:
  docker-image:
    runs-on: ubuntu-latest-8-cores
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up env vars
        shell: bash
        run: |
          maybe_branch=${GITHUB_HEAD_REF//\//-}
          BRANCH=${maybe_branch:-main}
          echo "BRANCH=${BRANCH}" >> "$GITHUB_ENV"
          if [ "$BRANCH" = "main" ]; then
            echo "BUILD_MODE=release" >> "$GITHUB_ENV"
          else
            echo "BUILD_MODE=debug" >> "$GITHUB_ENV"
          fi
        id: setup_env
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          file: ./Dockerfile
          build-args: |
            BUILD_MODE=${{ env.BUILD_MODE }}
          tags: |
            ghcr.io/kittycad/${{ github.event.repository.name }}:${{ env.BRANCH }}
            ghcr.io/kittycad/${{ github.event.repository.name }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha
